### ISSUE TITLE
Can I can a technical support without paying for the extension?

### ISSUE THREAD

**Issue by LeorentKelmendi** [mage2pro/moip#24]
I am getting this validation error, can not make any payment so far. Here is the error console on my browser. Any Idea how this could be handed ?

**Comment by dmitrii-fediuk** [comment]
I support the paying customers only.

**Comment by LeorentKelmendi** [comment]
Where I can reach you then ? @dmitry-fedyuk

**Comment by dmitrii-fediuk** [comment]
Ask all the question in the extension's forum branch: [mage2.pro/c/extensions/moip](https://mage2.pro/c/extensions/moip)
